<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="KeePass">
      <HintPath>C:\Programs\KeePass\2.60.0\windows\amd64\KeePass.exe</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
